name: VRChat Booth Checker

# This workflow runs on a schedule.
# '*/5 * * * *' means it will run every 5 minutes.
on:
  schedule:
    - cron: '*/5 * * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# FIXED: Added permissions for the workflow to write back to the repository.
permissions:
  contents: write

jobs:
  check-and-notify:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your repository's code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up the Python version
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 3: Install the required Python libraries
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      # Step 4: Run the bot script
      - name: Run VRChat Booth Bot
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python vrchat_bot.py

      # Step 5: Commit and push the updated last_item.txt file
      - name: Commit state file
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add last_item.txt || echo "No state file to commit"
          git commit -m "Update last seen item ID" || echo "No changes to commit"
          git push

